FROM pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-ubuntu-20.04-x86_64
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends fonts-wqy-microhei && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
